# Generated by Django 3.0.5 on 2023-05-20 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255)),
                ('mob_no', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('aadhar', models.FileField(max_length=255, upload_to='aadhar/')),
                ('pancard', models.FileField(max_length=255, upload_to='pancard/')),
                ('gender', models.CharField(max_length=255)),
                ('d_o_b', models.DateField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visa_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=255)),
                ('destination_country', models.CharField(max_length=255)),
                ('stay_duration', models.IntegerField()),
                ('photo', models.FileField(max_length=255, upload_to='photo/')),
                ('sign', models.FileField(max_length=255, upload_to='sign/')),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Visa')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
